"""Sync with current DB schema

Revision ID: cfe0c1374109
Revises: 
Create Date: 2025-08-06 01:35:13.972916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe0c1374109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_history', schema=None) as batch_op:
        batch_op.drop_column('to_stage_id')
        batch_op.drop_column('from_stage_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_stage_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('to_stage_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
